### ISSUE TITLE
Problem Attaching EBS-Volume to Windows on Eucalyptus

### ISSUE THREAD

**Issue by pascalschraml** [viglesiasce/EucaLobo#13]
When trying to attach an EBS-Volume to an existing Windows instance, we get the following error:

 "Please wait till 'Windows is Ready to use' before attaching an EBS volume to instance: test_instance | i-97345174 | m1.small | running"

We tracked the issue down and found that that the instance's log file gets checked for "Windows is Ready to use".
As we're using an Eucalyptus endpoint not AWS, this message never gets created.

The easiest fix would be to check whether the endpoint is AWS or not, and to sent the "Attach EBS" command anyways if it is not AWS.

**Comment by viglesiasce** [comment]
Fixed here f504654 and released in version 4.2.3.
