### ISSUE TITLE
Default option "Delete on Termination" when attaching EBS-Volume at instance launch

### ISSUE THREAD

**Issue by pascalschraml** [viglesiasce/EucaLobo#14]
When launching a new instance, there is an option to attach an exsiting EBS Volume automatically. Next to this, there's a checkbox, asking to "Delete on Termination".
By default, this is checked, so we're a bit worried users could delete their volumes by accident. Maybe you could change the default to unchecked?

**Comment by viglesiasce** [comment]
Fixed here 233e2b5  and released in version 4.2.3. Let me know how it looks.
